allowBuilds:
  core-js: false
  esbuild: true

minimumReleaseAgeExclude:
  - '@types/node@24.19.0'

patchedDependencies:
  '@suid/styled-engine': patches/@suid__styled-engine.patch
  '@suid/base': patches/@suid__base.patch
  '@suid/material': patches/@suid__material.patch
  '@material/tooltip': patches/@material__tooltip.patch
