// @ts-ignore
declare const notices: Array<Any>;
function makeTable(headers: string[], rows: string[][]) {
  return [
    `| ${headers.join(' | ')} |`,
    `| ${Array(headers.length).fill('---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}
function makeUrl(text: string, url: string) {
  return `[${text}](${url})`;
}

export default `<!-- Generated by 'pdm run docs_generate_os_notices', DO NOT DIRECTLY EDIT THIS FILE. -->
<!-- The template is located at 'docs/os_notices_template.py' -->
<!-- markdownlint-disable -->
<!-- @formatter:off -->

# 开源许可

${makeTable(
  ['开源项目', '许可证', '版权声明'],
  notices.map((notice) => [
    makeUrl(notice.name, notice.repository),
    notice.license,
    notice.copyrights?.join('<br />') ?? '',
  ]),
)}
`;
